# Generated by Django 6.1 on 2026-09-08 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_hora', models.DateTimeField()),
                ('asistencia', models.BooleanField(default=False)),
            ],
        ),
    ]
