# Generated by Django 6.1 on 2026-09-15 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_actividad_delete_turno'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Actividad',
        ),
    ]
